import React from 'react'
import Layout from '../Components/Layout/Layout'

const SectionCompany = () => {
  return (
    <Layout title={"Expert Section 8 Company Registration Services | Keyman Advisor"} description={"Start your non-profit venture with confidence using Keyman Advisor's expert advisory services for Section 8 Company registration. Our experienced advisors ensure a smooth registration process and compliance for your organization."} keywords={"Section 8 company registration advisor,Section 8 company registration services,Register Section 8 company online,Section 8 company incorporation assistance,Section 8 company formation consultant,Section 8 company registration process,Benefits of Section 8 company registration,Section 8 company compliance requirements,Section 8 company registration guidance,Expert Section 8 company advisors"}>

<section className="subpage-header">
			<div className="container">
				<div className="site-title clearfix">
					<h2>Section 8 Company  Registration</h2>
					<ul className="breadcrumbs">
						<li><a href="index.php">Home</a></li>
						<li>Section 8 Company  Registration</li>
					</ul>
				</div>
				<a href="contact-us.php" className="btn btn-primary get-in-touch" data-text="Contact us"><i className="icon-telephone114"></i>
				Section 8 Company  Registration</a>
			</div>
		</section>
		
		
		
		<section>
			<div className="container">
				
				<div className="row">
				
					<div className="col-md-12 animate fadeInRight">
						<div className="single-item-carousel  owl-carousel">
							<img src="images/services-img1.jpg" alt="" />
						</div>
						<br />
						<br />
						<h2>Overview of Section 8 Company Registration</h2>
						<p>A Section 8 company can be formed to promote art, science, commerce, technology, sports, education, social research, social welfare, religion, charity and environmental protection, among other things. After successfully completing the registration process, a Section 8 Company can operate anywhere in India.</p>
						<p>At least two directors are required to register a Section 8 entity. Furthermore, there is no requirement to secure a minimum paid-up capital in order to establish such a corporation. </p>
				   
						<br />
						<h3>What are the Benefits of Registering Section 8 Company in India.</h3>
						<p>Given below are the benefits of registering a section 8 company in India: </p>
						<ul style={{marginLeft:'10px'}}>
							<li> Section 8 companies registered under Section 12AA of the Income Tax Act enjoy a 100% tax exemption.</li>
							<li>The profits generated by Section 8 entities used for charitable purposes are entirely non-taxable.</li>
							<li>Enhanced financial resources lead to a more significant positive impact and more philanthropic activities for society.</li>
							<li>Section 8 companies are not subject to any minimum capital requirement, providing greater financial flexibility.</li>
							<li>Founders and stakeholders can determine the initial capital based on the organisation's needs and objectives</li>
							<li>The company can adjust its capital structure as it grows and expands its activities without legal constraints.</li>
							<li>Section 8 companies are exempt from paying stamp duty for registration, resulting in cost savings.</li>
							<li>Section 8 companies have the status of a separate legal entity, independent of their members or founders.</li>
							<li>Section 8 companies show higher credibility due to hard compliance requirements.</li>
							<li>Section 8 companies have the freedom to choose a name that reflects their mission and purpose.</li>
						</ul>
						<br />
						<br />
						 <h3>What are the Documents Required for Section 8 Company Registration?</h3>
						 <p>Given below are the essential documents needed for section 8 company registration in India:</p>
					
						<div className="row">
							<div className="col-md-12">
								<div className="chart-widget">
								<ul>
									<li>PAN Card of the Directors and Shareholders:</li>
									<li>Copy of the Rental Agreement, in case the property is on rent for the registered office</li>
									<li>Passport Size Photograph of all the Directors and Shareholders</li>
									<li>Voter ID or Passport or Driving License</li>
									<li>Telephone Bill or Electricity Bill</li>
									<li>Latest Bank Statement</li>
									<li>Aadhaar Card</li>
								  
								</ul>
								</div>
							</div>
						</div>

						</div>
						</div>
						</div>
						</section>

      
    </Layout>
  )
}

export default SectionCompany
